#!/usr/bin/python

# DEFAULT SYSTEM CONFIG MODULE FOR THE CYLC SYSTEM DEFINITION DIRECTORY:
#  /dvel/ecoconnect_dvel/cylc/sys/examples/nested

# REFER TO THE CYLC USER GUIDE FOR FULL DOCUMENTATION OF CONFIG ITEMS. 

# THIS FILE WAS AUTOGENERATED BY 'cylc configure'. You may want to
# comment tasks out of the task list in this file, to turn them off
# during incremental system testing, but BE AWARE THAT THIS FILE WILL BE
# OVERWRITTEN WHEN THE SYSTEM IS RECONFIGURED. Use the customizable
# module config_override.py to override default settings and set some
# additional config items ('task_groups', 'job_submit_overrides', and
# 'environment').

# Configured items are held in a dict (Python associative array): 
#   config[ 'item' ] = value.
# Note that some "values" are themselves lists or dicts.

import logging  # for logging level
import os       # os.environ['HOME']

# declare the main config container
config = {}

# LIST OF TASK NAMES (order irrelevant)
config['task_list'] = \
    [
       'F',
       'userguide_subsystem',
       'E',
       'X',
       'A',
       'D',
       'B',
       'coldstart',
       'startup',
    ]

# DEFAULT JOB SUBMIT METHOD FOR THIS SYSTEM
# value is a string that is the name of a class imported into the
# job_submit_methods module in the system definition directory.
# You can override this for the whole system, and for individual tasks,
# in the system config override module.
config['job_submit_method'] = 'background'

# LOGGING AND STATE DUMP DIRECTORIES
# the registered system name will automatically be appended to these 
# so that multiple instances of this system can run without interference.
config['logging_dir'] = 'CYLC/logfiles'
config['state_dump_dir'] = 'CYLC/statedumps'

# MAXIMUM INTERVAL (IN CYCLE TIME) BETWEEN FASTEST AND SLOWEST TASKS
config['max_runahead_hours'] = 24

# LOG VERBOSITY
config['logging_level'] = logging.INFO
#config['logging_level'] = logging.DEBUG

# END OF FILE
