#!/bin/bash

#         __________________________
#         |____C_O_P_Y_R_I_G_H_T___|
#         |                        |
#         |  (c) NIWA, 2008-2010   |
#         | Contact: Hilary Oliver |
#         |  h.oliver@niwa.co.nz   |
#         |    +64-4-386 0461      |
#         |________________________|


# Cylc task wrapper script

# Cylc tasks must send, at the least, their own 'started', 'succeeded',
# and 'failed' messages. This script allows cylc to control existing
# tasks that have not been modified to do their own cylc messaging.

# It does the following:
# (1) sends special 'started' message
# (2) executes the wrapped task (passes any commandline on)
# (3) sends the special 'succeed' message on completion,
#     or the special 'failed' message if an error occurs.

# It is assumed that wrapped tasks return the standard shell exit codes
# for success or failure. Wrapped tasks can also send their own cylc
# messages, but in that case you might as well dispense with wrapping
# and provide the started, finished, and failed messages as well.

set -e  # abort on error

# 'cylc message' checks for $TASK_NAME and $CYCLE_TIME  
# so we only need to check for $WRAP here.

if [[ -z $WRAP ]]; then
    echo "ERROR, cylc-wrapper: \$WRAP not found"
    exit 1
fi

# send the startup message
cylc message --started

# execute the wrapped task and check for success or failure
if $WRAP $@; then 
    # succeeded
    cylc message --all-outputs-completed
    cylc message --succeeded
else
    # failed
    cylc message --failed 
fi
