#!/usr/bin/python

# o SYSTEM CONFIG MODULE FOR THE CYLC SYSTEM DEFINITION DIRECTORY:
#  /dvel/ecoconnect_dvel/cylc/sys/examples/userguide
# o REFER TO THE CYLC USER GUIDE FOR DOCUMENTATION OF CONFIG ITEMS. 
# o THIS FILE WAS AUTOGENERATED BY 'cylc configure' BUT WILL NOT
# BE OVERWRITTEN ON RECONFIGURATION UNLESS YOU FORCE IT. 

# Configured items are held in a dict (Python associative array): 
#   items[ 'item' ] = value.
# Note that some "values" are themselves lists or dicts.

from config import config
from task_list import task_list
import logging  # for logging level
import os       # os.environ['HOME']

class system_config( config ):

    def __init__( self, sysname ):
        config.__init__( self, sysname )

        # system task list
        self.items['task_list'] = task_list

        # task insertion groups, e.g:
        # self.items['task_groups']['foo'] = ['bar', 'baz']

        # default job submit method, e.g.:
        # self.items['job_submit_method'] = 'background2'

        # environment variables available to all tasks
        user = os.environ['USER'] 
        self.items['environment']['TMPDIR'] = '/tmp/' + user + '/' + sysname
        self.items['environment']['REAL_TIME_ACCEL'] = 360


# END OF FILE
