#!/bin/bash
# THIS FILE IS PART OF THE CYLC SUITE ENGINE.
# Copyright (C) 2008-2017 NIWA
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------
# Check tasks and graph generated by parameter expansion.
. "$(dirname "$0")/test_header"
set_test_number 4

cat >'suite.rc' <<'__SUITE__'
[cylc]
    [[parameters]]
        i = cat, dog, fish
        j = 1..5
[scheduling]
    [[dependencies]]
        graph = """
foo => bar
"""
[runtime]
    [[root]]
        script = true
    [[foo<i, j>]]
    [[bar<i=cat, j=3>]]
        inherit = 'foo<i, j>'
__SUITE__

run_ok "${TEST_NAME_BASE}-1" cylc validate "suite.rc"

cat >'suite.rc' <<'__SUITE__'
[cylc]
    [[parameters]]
        i = 1..5
        j = cat, dog, fish
[scheduling]
    [[dependencies]]
        graph = """
foo => bar
"""
[runtime]
    [[root]]
        script = true
    [[foo<i, j>]]
    [[bar<i=3, j=dog>]]
        inherit = 'foo<i=3, j=dog>'
__SUITE__

run_ok "${TEST_NAME_BASE}-2" cylc validate "suite.rc"

cat >'suite.rc' <<'__SUITE__'
[cylc]
    [[parameters]]
        i = 1..5
        j = dog, cat, fish
[scheduling]
    [[dependencies]]
        graph = """
foo => bar
"""
[runtime]
    [[root]]
        script = true
    [[foo<i, j>]]
    [[bar<i=4, j=fish>]]
        inherit = 'foo<i=2, j=fish>'
__SUITE__

run_fail "${TEST_NAME_BASE}-3" cylc validate "suite.rc"
cmp_ok "${TEST_NAME_BASE}-3.stderr" <<'__ERR__'
ERROR, bad parameter value '2' in 'inherit = foo<i=2, j=fish>'
__ERR__

exit
