#!/bin/bash
# THIS FILE IS PART OF THE CYLC SUITE ENGINE.
# Copyright (C) 2008-2017 NIWA
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Check tasks and graph generated by parameter expansion.
. "$(dirname "$0")/test_header"
set_test_number 8

cat >'suite.rc' <<'__SUITE__'
[cylc]
    [[parameters]]
        i = cat, dog, fish
        j = 1..5
[scheduling]
    [[dependencies]]
        graph = """foo => bar<i,j>
                   bar<i=cat,j=3> => boo"""
[runtime]
    [[root]]
        script = true
    [[FAM<i,j>]]
    [[bar<i,j>]]
        inherit = "FAM<i,j>"
    [[bar<i=cat,j=3>]]
        inherit = "FAM<i,j>"  # implicit values here
__SUITE__

run_ok "${TEST_NAME_BASE}-1" cylc validate "suite.rc"

graph_suite "suite.rc" "graph.plain.1"
cmp_ok "graph.plain.1" "${TEST_SOURCE_DIR}/${TEST_NAME_BASE}/graph.plain.ref"

cat >'suite.rc' <<'__SUITE__'
[cylc]
    [[parameters]]
        i = cat, dog, fish
        j = 1..5
[scheduling]
    [[dependencies]]
        graph = """foo => bar<i,j>
                   bar<i=cat,j=3> => boo"""
[runtime]
    [[root]]
        script = true
    [[FAM<i,j>]]
    [[bar<i,j>]]
        inherit = "FAM<i,j>"
    [[bar<i=cat,j=3>]]
        inherit = "FAM<i=cat,j=3>"  # correct explicit values here
__SUITE__

run_ok "${TEST_NAME_BASE}-2" cylc validate "suite.rc"

graph_suite "suite.rc" "graph.plain.2"
cmp_ok "graph.plain.2" "${TEST_SOURCE_DIR}/${TEST_NAME_BASE}/graph.plain.ref"

cat >'suite.rc' <<'__SUITE__'
[cylc]
    [[parameters]]
        i = cat, dog, fish
        j = 1..5
[scheduling]
    [[dependencies]]
        graph = """foo => bar<i,j>
                   bar<i=cat,j=3> => boo"""
[runtime]
    [[root]]
        script = true
    [[FAM<i,j>]]
    [[bar<i,j>]]
        inherit = "FAM<i,j>"
    [[bar<i=cat,j=3>]]
        inherit = "FAM<i=dog,j=3>"  # bad explicit values here
__SUITE__

run_fail "${TEST_NAME_BASE}-3" cylc validate "suite.rc"
cmp_ok "${TEST_NAME_BASE}-3.stderr" <<'__ERR__'
ERROR, bad parameter value 'dog' in 'inherit = FAM<i=dog,j=3>'
__ERR__

# Test white space in the parameter syntax.
cat >'suite.rc' <<'__SUITE__'
[cylc]
    [[parameters]]
        i = cat, dog, fish
        j = 1..5
[scheduling]
    [[dependencies]]
        graph = """foo => bar< i ,j >
                   bar< i = cat , j = 3 > => boo"""
[runtime]
    [[root]]
        script = true
    [[FAM<i,j>]]
    [[bar<i,j>]]
        inherit = "FAM< i, j>"
    [[bar<i=cat,j=3>]]
        inherit = "FAM<i = cat ,j=3>"  # correct explicit values here
__SUITE__

run_ok "${TEST_NAME_BASE}-4" cylc validate "suite.rc"
graph_suite "suite.rc" "graph.plain.4"
cmp_ok "graph.plain.4" "${TEST_SOURCE_DIR}/${TEST_NAME_BASE}/graph.plain.ref"
