#!/usr/bin/env python

#         __________________________
#         |____C_O_P_Y_R_I_G_H_T___|
#         |                        |
#         |  (c) NIWA, 2008-2010   |
#         | Contact: Hilary Oliver |
#         |  h.oliver@niwa.co.nz   |
#         |    +64-4-386 0461      |
#         |________________________|

# o SUITE CONFIG MODULE FOR THE CYLC SUITE DEFINITION DIRECTORY:
#  /home/oliverh/cylc/suites/scs-demo
# o REFER TO THE CYLC USER GUIDE FOR DOCUMENTATION OF CONFIG ITEMS. 
# o THIS FILE WAS AUTOGENERATED BY 'cylc configure' BUT WILL NOT
# BE OVERWRITTEN ON RECONFIGURATION UNLESS YOU FORCE IT. 

# Configured items are held in a dict (Python associative array): 
#   items[ 'item' ] = value.
# Note that some "values" are themselves lists or dicts.

from config import config
from task_list import task_list, task_list_shortnames
from suite_info import info
import logging  # for logging level
import os       # os.environ['HOME']

class suite_config( config ):

    def __init__( self, suitename ):
        config.__init__( self, suitename )

        # suite title
        self.items[ 'suite_title' ] = 'SCS DEMO EXAMPLE'

        # multiple simultaneous suite instances?
        self.items[ 'allow_simultaneous_suite_instances' ] = False

        # suite info: add descriptive information as you like, e.g.:
        # self.items[ 'suite_info' ]['foo'] = 'foo bar baz'

        # suite task list
        self.items['task_list'] = task_list
        self.items['task_list_shortnames'] = task_list_shortnames

        # list of legal startup hours, if this suite is so restricted
        # e.g.: self.items['legal_startup_hours'] = [ 6 ]
        # or:   self.items['legal_startup_hours'] = [ 6, 18 ]
        self.items['legal_startup_hours'] = [ 6 ]

        # suite info
        self.items['suite_info']['info'] = info

        # task insertion groups, e.g:
        # self.items['task_groups']['foo'] = ['bar', 'baz']

        # default job submit method, e.g.:
        # self.items['job_submit_method'] = 'background2'

        # environment variables available to all tasks, can include
        # the registered suite name, e.g.:
        # user = os.environ['USER'] 
        # self.items['environment']['TMPDIR'] = '/tmp/' + user + '/' + suitename

# END OF FILE
