#!/usr/bin/python

# THIS IS A CYLC CONFIGURATION FILE FOR THE SYSTEM 
# /home/oliverh/cylc/sys/examples/simple-0
# IT WAS INITIALLY GENERATED BY 'cylc configure'.
# RECONFIGURING WILL NOT OVERWRITE UNLESS FORCED,
# because you may want to change default settings.

import logging  # for logging level
import os       # os.environ['HOME']

# config[ 'item_name' ] = item_value
config = {}

# SYSTEM NAME (also used as Pyro nameserver group)
config['system_name'] = 'foobar'

# LIST OF TASK NAMES
config['task_list'] = \
    [
       'B',
       'E',
       'ext',
       'A',
       'F',
       'startup',
       'D',
       'C',
    ]

# TASK GROUPS
config['task_groups'] = {}

# LOGGING DIRECTORY (default: in cwd)
config['logging_dir'] = 'CYLC-LOGS'

# STATE DUMP FILE (default: in cwd)
config['state_dump_dir'] = 'CYLC-STATE'
config['state_dump_file'] = 'state'

# ENVIRONMENT VARIABLES TO SET FOR USE BY EXTERNAL TASKS
# { VAR1:VALUE1, VAR2:VALUE2, ...}
config['environment'] = {'TMPDIR':'/tmp/' + os.environ['USER'] + '/' + config[ 'system_name' ]}

# MAXIMUM TIME ANY TASK IS ALLOWED TO GET AHEAD OF THE SLOWEST
config['max_runahead_hours'] = 24

# DUMMY MODE
config['dummy_mode'] = False

# JOB LAUNCH METHOD (qsub or background)
config['use_qsub'] = False
config['job_queue'] = None

 # LOG VERBOSITY
config['logging_level'] = logging.INFO
#config['logging_level'] = logging.DEBUG
