#!/bin/bash

set -e

# Generates pdf documentation from cylc LaTeX source.

usage() {
	echo "USAGE: [-f] $0"
    echo ' -f, force re-conversion of eps figures to PDF'
    echo "Run this script from \$CYLC_DIR"
}

[[ $# > 1 ]] && {
    usage
	exit 1
}

if [[ ! -f bin/cylc ]]; then
    echo "Run this script from \$CYLC_DIR"
    exit 1
fi

FORCE=false
if [[ $# == 1 ]]; then 
    if [[ $1 = '-f' ]]; then
        FORCE=true
    else
        usage
        exit 1
    fi
fi

# GENERATE COMMAND REFERENCE CHAPTER CONTENTS -----------------------
rm -rf doc/command-usage; mkdir -p doc/command-usage
rm -f doc/commands.tex

cylc help >> doc/command-usage/help.txt

# append to a latex file for inclusion in the userguide
echo "\label{help}" >> doc/commands.tex
echo "\lstinputlisting{command-usage/help.txt}" >> doc/commands.tex
#echo "\pagebreak" >> doc/commands.tex

echo "\subsection{Command Categories}" >> doc/commands.tex

for CAT in $(cylc categories); do 
    echo "o $CAT"
    # direct command help into a txt file
    cylc help $CAT >> doc/command-usage/$CAT.txt
    # append to a latex file for inclusion in the userguide
    echo "\subsubsection{$CAT}" >> doc/commands.tex
    echo "\label{$CAT}" >> doc/commands.tex
    echo "\lstinputlisting{command-usage/$CAT.txt}" >> doc/commands.tex
    #echo "\pagebreak" >> doc/commands.tex
done

echo "\subsection{Commands}" >> doc/commands.tex
for COMMAND in $(cylc commands); do 
    echo "+ $COMMAND"
    # direct command help into a txt file
    cylc $COMMAND --help > doc/command-usage/$COMMAND.txt
    # append to a latex file for inclusion in the userguide
    echo "\subsubsection{$COMMAND}" >> doc/commands.tex
    echo "\label{$COMMAND}" >> doc/commands.tex
    echo "\lstinputlisting{command-usage/$COMMAND.txt}" >> doc/commands.tex
    #echo "\pagebreak" >> doc/commands.tex
done

#-----------------------------------------------------------------------

cd doc

cd inkscape-svg
for F in *.eps; do
    [[ ! -f ${F%eps}pdf ]] || $FORCE && {
        echo converting $F to PDF
        epstopdf $F
    }
done
cd ..

#pdflatex userguide.tex
latex userguide.tex
dvipdf userguide.dvi
