#!/usr/bin/python

import sys
import cycle_time
from optparse import OptionParser

parser = OptionParser( usage = """cylc-time [options] CYCLE

Return the result of adding or subtracting a specified number of 
hours from a cylc cycle time (YYYYMMDDHH).""" )

parser.add_option( "-s", "--subtract", metavar="HOURS",
        help="Substract HOURS from CYCLE", action="store", dest="subtract" )

parser.add_option( "-a", "--add", metavar="HOURS",
        help="Add HOURS to CYCLE", action="store", dest="add" )

(options, args) = parser.parse_args()

if len( args ) != 1:
    parser.error( "Wrong number of arguments!" )

cycle = args[0]
if not cycle_time.is_valid( cycle ):
    parser.error( "invalid cycle time: " + cycle )

if not ( options.add or options.subtract ):
    parser.error( "Choose either subtract or add" )

if options.subtract and options.add:
    parser.error( "Choose either subtract or add" )

if options.add:
    try:
        hours = int( str( int( options.add )))
    except ValueError:
        raise SystemExit( "Bad HOURS" )
    else:
        print cycle_time.increment( cycle, hours )

if options.subtract:
    try:
        hours = int( str( int( options.subtract )))
    except ValueError:
        raise SystemExit( "Bad HOURS" )
    else:
        print cycle_time.decrement( cycle, hours )
