#!/usr/bin/env python

#         __________________________
#         |____C_O_P_Y_R_I_G_H_T___|
#         |                        |
#         |  (c) NIWA, 2008-2010   |
#         | Contact: Hilary Oliver |
#         |  h.oliver@niwa.co.nz   |
#         |    +64-4-386 0461      |
#         |________________________|


# REFER TO THE CYLC USER GUIDE FOR DOCUMENTATION OF CONFIG ITEMS. 
# THIS FILE WAS AUTOGENERATED BY 'cylc configure' BUT WILL NOT
# BE OVERWRITTEN ON RECONFIGURATION UNLESS YOU FORCE IT. 

# Configured items are held in a dict (Python associative array): 
#   items[ 'item' ] = value.
# Note that some "values" are themselves lists or dicts.

from config import config
from task_list import task_list, task_list_shortnames
from suite_info import info
import logging  # for logging level
import os       # os.environ['HOME']

class suite_config( config ):

    def __init__( self, suitename ):
        config.__init__( self, suitename )

        # suite title
        self.items[ 'suite_title' ] = 'USERGUIDE EXAMPLE SUITE'
        
        # suite info
        self.items['suite_info']['info'] = info   # SEE suite_info.py
        # add more descriptive information as you like, e.g.:
        # self.items[ 'suite_info' ]['colours'] = 'red, blue, green'

        # task list
        self.items['task_list'] = task_list    # SEE task_list.py
        self.items['task_list_shortnames'] = task_list_shortnames    # SEE task_list.py

        # task insertion groups, e.g:
        # self.items['task_groups']['foo'] = ['bar', 'baz']

        # list of legal startup hours, if this suite is so restricted
        # e.g.: self.items['legal_startup_hours'] = [ 6 ]
        # or:   self.items['legal_startup_hours'] = [ 6, 18 ]

        # default job submit method, e.g.:
        self.items['job_submit_method'] = 'background'
        #self.items['job_submit_method'] = 'background2'
        #self.items['job_submit_method'] = 'at_now'

        # to override the default job submit method for specific tasks, e.g.:
        # self.items['job_submit_overrides']['background2'] = [ 'task1', 'task2' ]
        #self.items['job_submit_overrides'][ 'background2' ] = [ 'A', 'B', 'C' ]
        #self.items['job_submit_overrides']['loadleveler_ecoconnect'] = [ 'A' ]

        # environment variables available to all tasks, can include
        # the registered suite name, e.g.:
        user = os.environ['USER']
        self.items['environment']['CYLC_TMPDIR'] = '/tmp/' + user + '/' + suitename

        # 2/ $REAL_TIME_ACCEL, used to scale real run times for fast operation 
        self.items['environment']['REAL_TIME_ACCEL'] = 360

        #self.items['logging_level'] = logging.DEBUG

# END OF FILE
