#!/usr/bin/env python

#C: THIS FILE IS PART OF THE CYLC FORECAST SUITE METASCHEDULER.
#C: Copyright (C) 2008-2011 Hilary Oliver, NIWA
#C:
#C: This program is free software: you can redistribute it and/or modify
#C: it under the terms of the GNU General Public License as published by
#C: the Free Software Foundation, either version 3 of the License, or
#C: (at your option) any later version.
#C:
#C: This program is distributed in the hope that it will be useful,
#C: but WITHOUT ANY WARRANTY; without even the implied warranty of
#C: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#C: GNU General Public License for more details.
#C:
#C: You should have received a copy of the GNU General Public License
#C: along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys, re
from cylc.cycle_time import ct, CycleTimeError
from optparse import OptionParser

parser = OptionParser( usage = """cylc [util] cycletime [options] [CYCLE]

Perform arithmetic operations on cycle times and print the results to 
sdtout. Examples:

   # offset from explicit cycle time:
   $ cylc cycletime -s 6 2010082318
  2010082312

   # offset from $CYLC_TASK_CYCLE_TIME:
   $ export CYLC_TASK_CYCLE_TIME=2010082318
   $ cylc cycletime -s 6 
  2010082312

Arguments:
   CYCLE        (YYYYMMDDHH) defaults to $CYLC_TASK_CYCLE_TIME.""" )

parser.add_option( "-s", "--subtract", metavar="HOURS",
        help="Subtract HOURS from CYCLE", 
        action="store", dest="subtract" )

parser.add_option( "-a", "--add", metavar="HOURS",
        help="Add HOURS to CYCLE", 
        action="store", dest="add" )

parser.add_option( "-o", "--offset", metavar="HOURS",
        help="Apply an offset of +/-HOURS to CYCLE", 
        action="store", dest="offset" )

parser.add_option( "--year", help="Print only YYYY of result",
        action="store_true", default=False, dest="print_year" )

parser.add_option( "--month", help="Print only MM of result",
        action="store_true", default=False, dest="print_month" )

parser.add_option( "--day", help="Print only DD of result",
        action="store_true", default=False, dest="print_day" )

parser.add_option( "--hour", help="Print only HH of result",
        action="store_true", default=False, dest="print_hour" )

(options, args) = parser.parse_args()

if len( args ) == 0:
    # input cycle time must be definied in the environment.
    if 'CYLC_TASK_CYCLE_TIME' not in os.environ:
        parser.error( "Provide CYCLE arg, or define $CYLC_TASK_CYCLE_TIME" )
    else:
        try:
            cycle = ct(os.environ[ 'CYLC_TASK_CYCLE_TIME' ])
        except CycleTimeError, x:
            raise SystemExit(x)
    # DONE (no args)

elif len( args ) == 1:
    # must be cycle time
    try:
        cycle = ct(args[0])
    except CycleTimeError, x:
        raise SystemExit(x)
else:
    parser.error( "Wrong number of arguments!" )

n_chosen = 0
subtract = False
add = False
offset = False

hours_str = int( cycle.hour ) 

if options.subtract:
    subtract = True
    n_chosen += 1 
    try:
        hours_str = int( options.subtract )
    except ValueError:
        parser.error( 'ERROR: you can only subtract integer hours' )

if options.add:
    add = True
    n_chosen += 1
    try:
        hours_str = int( options.add )
    except ValueError:
        parser.error( 'ERROR: you can only add integer hours' )

if options.offset:
    offset = True
    n_chosen += 1
    try:
        hours_str = int( options.offset )
    except ValueError:
        parser.error( 'ERROR: you can only offset integer hours' )

if n_chosen > 1:
    parser.error( "Choose ZERO or ONE of subtract, add, or offset" )

n_chosen = 0
print_year = False
print_month = False
print_day = False
print_hour = False

if options.print_year:
    n_chosen +=1
    print_year = True

if options.print_month:
    n_chosen +=1
    print_month = True

if options.print_day:
    n_chosen +=1
    print_day = True

if options.print_hour:
    n_chosen +=1
    print_hour = True

if n_chosen != 0 and n_chosen != 1:
    parser.error( "Choose NONE or ONE of print_(year|month|day|hour)" )

try:
    hours = int( hours_str )
except ValueError:
    parser.error( "HOURS must be integer" )

if offset:
    if hours < 0:
        subtract = True
        hours = - hours
    else:
        add = True

if add:
    cycle.increment( hours=hours )
elif subtract:
    cycle.decrement( hours=hours )

if print_year:
    print cycle.year
elif print_month:
    print cycle.month
elif print_day:
    print cycle.day
elif print_hour:
    print cycle.hour
else:
    print cycle.get()
