#!/bin/bash

# A cylc task event hook script that sends an email when called. 

# Cylc calls event hook scripts with the following arguments:
#   EVENT SUITE TASKID MESSAGE
# See the Cylc User Guide Suite.rc Reference for more information.

usage() {
    echo "USAGE: cylc email-alert EVENT SUITE TASKID MESSAGE"
    echo ""
    echo "A cylc event hook script that sends an email alert. The arguments"
    echo "are supplied automatically by cylc. To get an email alert whenever"
    echo "a task in your suite fails, for example, do this:"
    echo ""
    echo "# SUITE.RC"
    echo "[cylc]"
    echo "   [[environment]]"
    echo "      MAIL_ADDRESS = foo@bar.baz.waz"
    echo "[runtime]"
    echo "   [[__NAME__]]  # (namespace: 'root' or family or task name)"
    echo "      [[[event hooks]]]"
    echo "         events = failed"
    echo "         script = cylc email-alert"
    echo ""
    echo "See the Suite.rc Reference (Cylc User Guide) for details."
}

if [[ $# = 1 ]]; then
    if [[ $1 = '--help' ]]; then
        usage
        exit 0
    fi
fi

if [[ $# < 4 ]]; then
    usage
    exit 1
fi

EVENT=$1      # e.g. "failed"
SUITE=$2      # group:name of the [failed] task
TASKID=$3       # name of the [failed] task 
MESSAGE="$4"  # quotes required (message contains spaces)

MAIL_SUBJECT="!!cylc alert!! $SUITE $TASKID $EVENT" 
MAIL_ADDRESS=${MAIL_ADDRESS:-$USER@$HOSTNAME}
MAIL_BODY="SUITE: $SUITE
TASK: $TASKID
MESSAGE: $MESSAGE"

echo "$MAIL_BODY" | mail -s "$MAIL_SUBJECT" $MAIL_ADDRESS
