#!/usr/bin/env python

#C: THIS FILE IS PART OF THE CYLC FORECAST SUITE METASCHEDULER.
#C: Copyright (C) 2008-2012 Hilary Oliver, NIWA
#C:
#C: This program is free software: you can redistribute it and/or modify
#C: it under the terms of the GNU General Public License as published by
#C: the Free Software Foundation, either version 3 of the License, or
#C: (at your option) any later version.
#C:
#C: This program is distributed in the hope that it will be useful,
#C: but WITHOUT ANY WARRANTY; without even the implied warranty of
#C: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#C: GNU General Public License for more details.
#C:
#C: You should have received a copy of the GNU General Public License
#C: along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys
import random
from optparse import OptionParser

parser = OptionParser( usage = """cylc [util] random A B

Generate a random integer in the range [A,B). This is just a command
interface to Python's random.randrange() function. 

Arguments:
   A     start of the range interval (inclusive)
   B     end of the random range (exclusive, so must be > A)""")

(options, args) = parser.parse_args()

if len( args ) != 2:
    parser.error( "Two integer arguments required" )

try:
    start = int(args[0])
    end = int(args[1])
    print random.randrange( start, end )
except ValueError, x:
    raise SystemExit(x)

