#!/bin/bash
#C: THIS FILE IS PART OF THE CYLC SUITE ENGINE.
#C: Copyright (C) 2008-2013 Hilary Oliver, NIWA
#C: 
#C: This program is free software: you can redistribute it and/or modify
#C: it under the terms of the GNU General Public License as published by
#C: the Free Software Foundation, either version 3 of the License, or
#C: (at your option) any later version.
#C:
#C: This program is distributed in the hope that it will be useful,
#C: but WITHOUT ANY WARRANTY; without even the implied warranty of
#C: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#C: GNU General Public License for more details.
#C:
#C: You should have received a copy of the GNU General Public License
#C: along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# NAME
#     test_header
#
# SYNOPSIS
#     . $CYLC_DIR/t/lib/bash/test_header
#
# DESCRIPTION
#     Interface for constructing tests under a TAP harness (the "prove"
#     command).
#
# FUNCTIONS
#     set_test_number N
#         echo a total number of tests for TAP to read.
#     ok TEST_NAME
#         echo a TAP OK message for TEST_NAME.
#     fail TEST_NAME
#         echo a TAP fail message for TEST_NAME.
#     run_ok TEST_NAME COMMAND ...
#         Run COMMAND with any following options/arguments and store stdout
#         and stderr in TEST_NAME.stdout and TEST_NAME.stderr.
#         This is expected to have a return code of 0, which ok's the test.
#     run_fail TEST_NAME COMMAND ...
#         Run COMMAND with any following options/arguments and store stdout
#         and stderr in TEST_NAME.stdout and TEST_NAME.stderr.
#         This is expected to have a non-zero return code, which ok's the test.
#     cmp_ok TEST_NAME FILE_TEST [FILE_CONTROL]
#         Compare FILE_TEST with a file or stdin given by FILE_CONTROL
#         (stdin if FILE_CONTROL is "-" or missing). If $TEST_DEBUG_CMP
#         is set, show differences using xxdiff.
#     grep_ok TEST_NAME GREP_BRE FILE
#         Run "grep -q GREP_BRE FILE".
#     init_suite SUITE_NAME
#         Create a suite called '__cylc__test__${SUITE_NAME}__' in $TEST_DIR.
#     purge_suite SUITE_NAME
#         Tidy up test directories for SUITE_NAME.
#-------------------------------------------------------------------------------
set -eu

SIGNALS="EXIT INT"
TEST_DIR=
function FINALLY() {
    for S in $SIGNALS; do
        trap '' $S
    done
    if [[ -n $TEST_DIR ]]; then
        cd ~
        rm -rf $TEST_DIR
    fi
}
for S in $SIGNALS; do
    trap "FINALLY $S" $S
done

TEST_NUMBER=0

function set_test_number() {
    echo "1..$1"
}

function ok() {
    echo "ok $((++TEST_NUMBER)) - $@"
}

function fail() {
    echo "not ok $((++TEST_NUMBER)) - $@"
}

function run_ok() {
    local TEST_NAME=$1
    shift 1
    if ! "$@" 1>$TEST_NAME.stdout 2>$TEST_NAME.stderr; then
        fail $TEST_NAME
        return
    fi
    ok $TEST_NAME
}

function run_fail() {
    local TEST_NAME=$1
    shift 1
    if "$@" 1>$TEST_NAME.stdout 2>$TEST_NAME.stderr; then
        fail $TEST_NAME
        return
    fi
    ok $TEST_NAME
}

function cmp_ok() {
    local FILE_TEST=$1
    local FILE_CONTROL=${2:--}
    local TEST_NAME=$(basename $FILE_TEST)
    local CMP_COMMAND="cmp"
    if [[ -n ${TEST_DEBUG_CMP:-} ]]; then
        CMP_COMMAND="xxdiff -D"
    fi
    if $CMP_COMMAND $FILE_TEST $FILE_CONTROL; then
        ok $TEST_NAME
        return
    fi
    fail $TEST_NAME
}

function grep_ok() {
    local TEST_NAME=$1
    local BRE=$2
    local FILE=$3
    if grep -q -e "$BRE" $FILE; then
        ok $TEST_NAME
        return
    fi
    fail $TEST_NAME
}

function init_suite() {
    SUITE_NAME=cylc_test_${1}
    mkdir $TEST_DIR/$SUITE_NAME/ 2>&1 
    cat >$TEST_DIR/$SUITE_NAME/suite.rc
    cylc unregister $SUITE_NAME 2>&1
    cylc register $SUITE_NAME $TEST_DIR/$SUITE_NAME 2>&1 
    cd $TEST_DIR/$SUITE_NAME 2>&1 
}

function purge_suite() {
    cd $TEST_DIR
    if [[ -n ${SUITE_NAME:-} ]]; then
        cylc unregister $SUITE_NAME || true
        if [[ -n ${TEST_DIR:-} ]]; then
            rm -rf $TEST_DIR/$SUITE_NAME/
        fi
    fi
}

CYLC_DIR=${CYLC_DIR:-$(cd $(dirname $BASH_SOURCE)/../../.. && pwd)}
PATH=$CYLC_DIR/bin:$PATH

TEST_NAME_BASE=$(basename $0 .t)
TEST_SOURCE_DIR=$(cd $(dirname $0) && pwd)
TEST_DIR=$(mktemp -d)
cd $TEST_DIR

set +e
