#!/bin/bash

#C: THIS FILE IS PART OF THE CYLC SUITE ENGINE.
#C: Copyright (C) 2008-2013 Hilary Oliver, NIWA
#C: 
#C: This program is free software: you can redistribute it and/or modify
#C: it under the terms of the GNU General Public License as published by
#C: the Free Software Foundation, either version 3 of the License, or
#C: (at your option) any later version.
#C:
#C: This program is distributed in the hope that it will be useful,
#C: but WITHOUT ANY WARRANTY; without even the implied warranty of
#C: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#C: GNU General Public License for more details.
#C:
#C: You should have received a copy of the GNU General Public License
#C: along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script determines the cylc version string in a repository clone
# and echoes it to stdout. It is executed by lib/cylc/version.py when
# cylc is run out of a repository.  The version string is returned by
# 'git describe' and then "-dirty" is appended if the working directory
# is not clean.

LF='
'

VN=$(git describe --abbrev=4 HEAD 2>/dev/null)
case "$VN" in
    *$LF*) (exit 1) ;;
    [0-9]*)
        # if uncommited changes exist append "-dirty"
        git update-index -q --refresh
        test -z "$(git diff-index --name-only HEAD --)" || VN="$VN-dirty" ;;
esac
# echo to stdout
echo "$VN"

